
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
# payment Service Job
  payment-service:
    name: payment Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for payment Service
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies for payment Service
        run: npm install

      - name: Build Docker image for payment Service
        run: docker build -t cr-payment .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push payment Service to Docker Hub
        run: |
          docker tag cr-payment ${{ secrets.DOCKER_USERNAME }}/cr-payment:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cr-payment:latest